services:
  stats-server:
    build:
      context: ./ewm-stats-service/stats-server
    image: ewm-stats-server
    container_name: ewm-stats-server
    depends_on:
      stats-db:
        condition: service_healthy
    ports:
      - "9090:9090"
    environment:
      STATS_SERVER_PORT: 9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/ewm_stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats

  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: ewm_stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    volumes:
      - stats-db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U stats -d ewm_stats
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  stats-db-data:
