server.port=${MAIN_SERVER_PORT:8080}

spring.application.name=ewm-main-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm_main}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:main}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:main}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

stats-server.url=${STATS_SERVER_URL:http://localhost:9090}

management.endpoints.web.exposure.include=health,info
